// This file was generated by SquareLine Studio
// Modified to add loading bar auto transition
// SquareLine Studio version: 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#include "ui.h"
#include "ui_helpers.h"

#include "ui_Screen1.h"   // Contains ui_barloading
#include "ui_Screen2.h"   // Target screen after loading

///////////////////// VARIABLES ////////////////////

lv_obj_t *ui____initial_actions0;

// Loading variables
static lv_timer_t * loading_timer;
static int loading_value = 0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// FUNCTIONS ////////////////////

static void loading_timer_cb(lv_timer_t * timer)
{
    LV_UNUSED(timer);

    loading_value += 2;   // Loading speed (increase for faster)

    lv_bar_set_value(ui_barloading, loading_value, LV_ANIM_ON);

    if(loading_value >= 100)
    {
        lv_timer_del(loading_timer);

        // Switch to Screen2 with fade animation
        lv_scr_load_anim(ui_Screen2,
                         LV_SCR_LOAD_ANIM_FADE_ON,
                         500,     // animation time
                         0,       // delay
                         false);  // no auto delete
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();

    lv_theme_t *theme = lv_theme_default_init(
        dispp,
        lv_palette_main(LV_PALETTE_BLUE),
        lv_palette_main(LV_PALETTE_RED),
        true,
        LV_FONT_DEFAULT
    );

    lv_disp_set_theme(dispp, theme);

    // Initialize all screens
    ui_Screen1_screen_init();   // Loading screen
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui_Screen6_screen_init();
    ui_Screen7_screen_init();
    ui_Screen8_screen_init();
    ui_Screen9_screen_init();
    ui_Screen10_screen_init();
    ui_Screen11_screen_init();
    ui_Screen12_screen_init();
    ui_Screen13_screen_init();

    ui____initial_actions0 = lv_obj_create(NULL);

    // Start from Screen1 (Loading screen)
    lv_disp_load_scr(ui_Screen1);

    // Reset loading bar
    loading_value = 0;
    lv_bar_set_value(ui_barloading, 0, LV_ANIM_OFF);

    // Start timer (120ms interval)
    loading_timer = lv_timer_create(loading_timer_cb, 120, NULL);
}

void ui_destroy(void)
{
    ui_Screen1_screen_destroy();
    ui_Screen2_screen_destroy();
    ui_Screen3_screen_destroy();
    ui_Screen4_screen_destroy();
    ui_Screen5_screen_destroy();
    ui_Screen6_screen_destroy();
    ui_Screen7_screen_destroy();
    ui_Screen8_screen_destroy();
    ui_Screen9_screen_destroy();
    ui_Screen10_screen_destroy();
    ui_Screen11_screen_destroy();
    ui_Screen12_screen_destroy();
    ui_Screen13_screen_destroy();
}
