// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#ifndef UI_SCREEN9_H
#define UI_SCREEN9_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen9
extern void ui_Screen9_screen_init(void);
extern void ui_Screen9_screen_destroy(void);
extern lv_obj_t *ui_Screen9;
extern void ui_event_Button15( lv_event_t * e);
extern lv_obj_t *ui_Button15;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Button12;
extern lv_obj_t *ui_Label33;
extern lv_obj_t *ui_Panel20;
extern lv_obj_t *ui_Label34;
extern lv_obj_t *ui_Panel21;
extern lv_obj_t *ui_Image10;
extern lv_obj_t *ui_Label36;
extern lv_obj_t *ui_Panel22;
extern lv_obj_t *ui_Image12;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

