// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#include "ui.h"

lv_obj_t *ui_Screen9 = NULL;lv_obj_t *ui_Button15 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Button12 = NULL;lv_obj_t *ui_Label33 = NULL;lv_obj_t *ui_Panel20 = NULL;lv_obj_t *ui_Label34 = NULL;lv_obj_t *ui_Panel21 = NULL;lv_obj_t *ui_Image10 = NULL;lv_obj_t *ui_Label36 = NULL;lv_obj_t *ui_Panel22 = NULL;lv_obj_t *ui_Image12 = NULL;
// event funtions
void ui_event_Button15( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
}
}

// build funtions

void ui_Screen9_screen_init(void)
{
ui_Screen9 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen9, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button15 = lv_btn_create(ui_Screen9);
lv_obj_set_width( ui_Button15, 183);
lv_obj_set_height( ui_Button15, 119);
lv_obj_set_x( ui_Button15, -123 );
lv_obj_set_y( ui_Button15, 57 );
lv_obj_set_align( ui_Button15, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Button15, LV_STATE_PRESSED );     /// States
lv_obj_add_flag( ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Button15);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 2 );
lv_obj_set_y( ui_Label1, 2 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"OPEN");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button12 = lv_btn_create(ui_Screen9);
lv_obj_set_width( ui_Button12, 183);
lv_obj_set_height( ui_Button12, 119);
lv_obj_set_x( ui_Button12, 126 );
lv_obj_set_y( ui_Button12, 56 );
lv_obj_set_align( ui_Button12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x00A63E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label33 = lv_label_create(ui_Button12);
lv_obj_set_width( ui_Label33, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label33, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label33, -1 );
lv_obj_set_y( ui_Label33, 2 );
lv_obj_set_align( ui_Label33, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label33,"CLOSE");
lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel20 = lv_obj_create(ui_Screen9);
lv_obj_set_width( ui_Panel20, 450);
lv_obj_set_height( ui_Panel20, 86);
lv_obj_set_x( ui_Panel20, -3 );
lv_obj_set_y( ui_Panel20, -63 );
lv_obj_set_align( ui_Panel20, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel20, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel20, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label34 = lv_label_create(ui_Panel20);
lv_obj_set_width( ui_Label34, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label34, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label34, 1 );
lv_obj_set_y( ui_Label34, -8 );
lv_obj_set_align( ui_Label34, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label34,"DOOR CONTROL");
lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel21 = lv_obj_create(ui_Screen9);
lv_obj_set_width( ui_Panel21, 490);
lv_obj_set_height( ui_Panel21, 33);
lv_obj_set_x( ui_Panel21, 0 );
lv_obj_set_y( ui_Panel21, -144 );
lv_obj_set_align( ui_Panel21, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel21, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel21, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel21, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel21, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel21, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image10 = lv_img_create(ui_Panel21);
lv_img_set_src(ui_Image10, &ui_img_1046367525);
lv_obj_set_width( ui_Image10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image10, 401 );
lv_obj_set_y( ui_Image10, -13 );
lv_obj_add_flag( ui_Image10, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label36 = lv_label_create(ui_Panel21);
lv_obj_set_width( ui_Label36, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label36, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label36, 214 );
lv_obj_set_y( ui_Label36, -2 );
lv_obj_set_align( ui_Label36, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label36,"Online");
lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0x05DF72), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label36, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel22 = lv_obj_create(ui_Screen9);
lv_obj_set_width( ui_Panel22, 45);
lv_obj_set_height( ui_Panel22, 33);
lv_obj_set_x( ui_Panel22, -214 );
lv_obj_set_y( ui_Panel22, -140 );
lv_obj_set_align( ui_Panel22, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel22, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel22, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel22, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel22, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel22, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image12 = lv_img_create(ui_Panel22);
lv_img_set_src(ui_Image12, &ui_img_1046361127);
lv_obj_set_width( ui_Image12, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image12, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image12, -9 );
lv_obj_set_y( ui_Image12, -16 );
lv_obj_add_flag( ui_Image12, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);

}

void ui_Screen9_screen_destroy(void)
{
   if (ui_Screen9) lv_obj_del(ui_Screen9);

// NULL screen variables
ui_Screen9= NULL;
ui_Button15= NULL;
ui_Label1= NULL;
ui_Button12= NULL;
ui_Label33= NULL;
ui_Panel20= NULL;
ui_Label34= NULL;
ui_Panel21= NULL;
ui_Image10= NULL;
ui_Label36= NULL;
ui_Panel22= NULL;
ui_Image12= NULL;

}
