// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t *ui_Screen3;
extern void ui_event_Panel12( lv_event_t * e);
extern lv_obj_t *ui_Panel12;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Panel13;
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_Button8;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_Button9;
extern lv_obj_t *ui_Label21;
extern lv_obj_t *ui_Button10;
extern lv_obj_t *ui_Label22;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

