// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern lv_obj_t *ui_Screen6;

extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Label13;           // Main dispensing headline
extern lv_obj_t *ui_Label14;           // Subtitle / IR detail
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Spinner1;          // Active spinner

extern lv_obj_t *ui_Label_ir_status;   // IR chute sensor readout
extern lv_obj_t *ui_Label_batch_stat;  // Batch verified badge
extern lv_obj_t *ui_Btn_dispense_home; // Return to Home button

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
