// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#ifndef UI_SCREEN13_H
#define UI_SCREEN13_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen13
extern void ui_Screen13_screen_init(void);
extern void ui_Screen13_screen_destroy(void);
extern lv_obj_t *ui_Screen13;

extern lv_obj_t *ui_Panel_alarm_card;
extern lv_obj_t *ui_Label38;               // Excursion Alert Title
extern lv_obj_t *ui_Label_alarm_sub;
extern lv_obj_t *ui_Label_alarm_msg;
extern lv_obj_t *ui_Btn_alarm_reset;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
