// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#include "ui.h"

lv_obj_t *ui_Screen3 = NULL;lv_obj_t *ui_Panel12 = NULL;lv_obj_t *ui_Image5 = NULL;lv_obj_t *ui_Panel13 = NULL;lv_obj_t *ui_Button5 = NULL;lv_obj_t *ui_Label17 = NULL;lv_obj_t *ui_Button6 = NULL;lv_obj_t *ui_Label18 = NULL;lv_obj_t *ui_Button7 = NULL;lv_obj_t *ui_Label19 = NULL;lv_obj_t *ui_Button8 = NULL;lv_obj_t *ui_Label20 = NULL;lv_obj_t *ui_Button9 = NULL;lv_obj_t *ui_Label21 = NULL;lv_obj_t *ui_Button10 = NULL;lv_obj_t *ui_Label22 = NULL;
// event funtions
void ui_event_Panel12( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
}
}

// build funtions

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel12 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_Panel12, 56);
lv_obj_set_height( ui_Panel12, 33);
lv_obj_set_x( ui_Panel12, -209 );
lv_obj_set_y( ui_Panel12, -141 );
lv_obj_set_align( ui_Panel12, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image5 = lv_img_create(ui_Panel12);
lv_img_set_src(ui_Image5, &ui_img_1046361127);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image5, -9 );
lv_obj_set_y( ui_Image5, -16 );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel13 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_Panel13, 436);
lv_obj_set_height( ui_Panel13, 251);
lv_obj_set_x( ui_Panel13, 0 );
lv_obj_set_y( ui_Panel13, 7 );
lv_obj_set_align( ui_Panel13, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button5 = lv_btn_create(ui_Panel13);
lv_obj_set_width( ui_Button5, 112);
lv_obj_set_height( ui_Button5, 103);
lv_obj_set_x( ui_Button5, -146 );
lv_obj_set_y( ui_Button5, -61 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label17 = lv_label_create(ui_Button5);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"ENO");
lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button6 = lv_btn_create(ui_Panel13);
lv_obj_set_width( ui_Button6, 112);
lv_obj_set_height( ui_Button6, 103);
lv_obj_set_x( ui_Button6, -1 );
lv_obj_set_y( ui_Button6, -62 );
lv_obj_set_align( ui_Button6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label18 = lv_label_create(ui_Button6);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"ORS");
lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button7 = lv_btn_create(ui_Panel13);
lv_obj_set_width( ui_Button7, 112);
lv_obj_set_height( ui_Button7, 103);
lv_obj_set_x( ui_Button7, 141 );
lv_obj_set_y( ui_Button7, -61 );
lv_obj_set_align( ui_Button7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label19 = lv_label_create(ui_Button7);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"PARACETAMOL");
lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button8 = lv_btn_create(ui_Panel13);
lv_obj_set_width( ui_Button8, 112);
lv_obj_set_height( ui_Button8, 103);
lv_obj_set_x( ui_Button8, -141 );
lv_obj_set_y( ui_Button8, 63 );
lv_obj_set_align( ui_Button8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label20 = lv_label_create(ui_Button8);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"DSR");
lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button9 = lv_btn_create(ui_Panel13);
lv_obj_set_width( ui_Button9, 112);
lv_obj_set_height( ui_Button9, 103);
lv_obj_set_x( ui_Button9, 3 );
lv_obj_set_y( ui_Button9, 62 );
lv_obj_set_align( ui_Button9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label21 = lv_label_create(ui_Button9);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"SPAS");
lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button10 = lv_btn_create(ui_Panel13);
lv_obj_set_width( ui_Button10, 112);
lv_obj_set_height( ui_Button10, 103);
lv_obj_set_x( ui_Button10, 145 );
lv_obj_set_y( ui_Button10, 62 );
lv_obj_set_align( ui_Button10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label22 = lv_label_create(ui_Button10);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"CETRIZ");
lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Panel12, ui_event_Panel12, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
   if (ui_Screen3) lv_obj_del(ui_Screen3);

// NULL screen variables
ui_Screen3= NULL;
ui_Panel12= NULL;
ui_Image5= NULL;
ui_Panel13= NULL;
ui_Button5= NULL;
ui_Label17= NULL;
ui_Button6= NULL;
ui_Label18= NULL;
ui_Button7= NULL;
ui_Label19= NULL;
ui_Button8= NULL;
ui_Label20= NULL;
ui_Button9= NULL;
ui_Label21= NULL;
ui_Button10= NULL;
ui_Label22= NULL;

}
