// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#ifndef UI_SCREEN12_H
#define UI_SCREEN12_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen12
extern void ui_Screen12_screen_init(void);
extern void ui_Screen12_screen_destroy(void);
extern lv_obj_t *ui_Screen12;

// Header & back button
extern lv_obj_t *ui_Panel27;
extern lv_obj_t *ui_Image14;
extern lv_obj_t *ui_Label_scr12_title;

// Diagnostic Report Card
extern lv_obj_t *ui_Panel28;
extern lv_obj_t *ui_Label39;       // Report header
extern lv_obj_t *ui_Label41;       // Dynamic report text updated by Lib.ino

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
