// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#include "ui.h"

lv_obj_t *ui_Screen13 = NULL;lv_obj_t *ui_Label38 = NULL;
// event funtions

// build funtions

void ui_Screen13_screen_init(void)
{
ui_Screen13 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen13, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label38 = lv_label_create(ui_Screen13);
lv_obj_set_width( ui_Label38, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label38, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label38, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label38,"ERROR");
lv_obj_set_style_text_font(ui_Label38, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen13_screen_destroy(void)
{
   if (ui_Screen13) lv_obj_del(ui_Screen13);

// NULL screen variables
ui_Screen13= NULL;
ui_Label38= NULL;

}
