// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#ifndef UI_SCREEN11_H
#define UI_SCREEN11_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen11
extern void ui_Screen11_screen_init(void);
extern void ui_Screen11_screen_destroy(void);
extern lv_obj_t *ui_Screen11;
extern lv_obj_t *ui_Panel26;
extern lv_obj_t *ui_Image11;
extern lv_obj_t *ui_Panel25;
extern lv_obj_t *ui_Label35;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

