// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#include "ui.h"

lv_obj_t *ui_Screen7 = NULL;lv_obj_t *ui_Panel11 = NULL;lv_obj_t *ui_Image6 = NULL;lv_obj_t *ui_Panel10 = NULL;lv_obj_t *ui_Label15 = NULL;lv_obj_t *ui_Label16 = NULL;lv_obj_t *ui_Panel15 = NULL;lv_obj_t *ui_Image7 = NULL;lv_obj_t *ui_Spinner2 = NULL;
// event funtions

// build funtions

void ui_Screen7_screen_init(void)
{
ui_Screen7 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen7, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel11 = lv_obj_create(ui_Screen7);
lv_obj_set_width( ui_Panel11, 45);
lv_obj_set_height( ui_Panel11, 33);
lv_obj_set_x( ui_Panel11, -214 );
lv_obj_set_y( ui_Panel11, -140 );
lv_obj_set_align( ui_Panel11, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image6 = lv_img_create(ui_Panel11);
lv_img_set_src(ui_Image6, &ui_img_1046361127);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image6, -9 );
lv_obj_set_y( ui_Image6, -16 );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel10 = lv_obj_create(ui_Screen7);
lv_obj_set_width( ui_Panel10, 332);
lv_obj_set_height( ui_Panel10, 92);
lv_obj_set_x( ui_Panel10, 0 );
lv_obj_set_y( ui_Panel10, -67 );
lv_obj_set_align( ui_Panel10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label15 = lv_label_create(ui_Panel10);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, -1 );
lv_obj_set_y( ui_Label15, -21 );
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"Measure SpO2  & Temp");
lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label16 = lv_label_create(ui_Panel10);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, 0 );
lv_obj_set_y( ui_Label16, 7 );
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"Place finger on sensor");
lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel15 = lv_obj_create(ui_Screen7);
lv_obj_set_width( ui_Panel15, 113);
lv_obj_set_height( ui_Panel15, 111);
lv_obj_set_x( ui_Panel15, 2 );
lv_obj_set_y( ui_Panel15, 45 );
lv_obj_set_align( ui_Panel15, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel15, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x314158), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel15, lv_color_hex(0x314158), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image7 = lv_img_create(ui_Panel15);
lv_img_set_src(ui_Image7, &ui_img_1046363177);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 72
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 72
lv_obj_set_x( ui_Image7, 0 );
lv_obj_set_y( ui_Image7, -1 );
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinner2 = lv_spinner_create(ui_Screen7,1000,90);
lv_obj_set_width( ui_Spinner2, 80);
lv_obj_set_height( ui_Spinner2, 47);
lv_obj_set_x( ui_Spinner2, 212 );
lv_obj_set_y( ui_Spinner2, 122 );
lv_obj_set_align( ui_Spinner2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner2, LV_OBJ_FLAG_CLICKABLE );    /// Flags

}

void ui_Screen7_screen_destroy(void)
{
   if (ui_Screen7) lv_obj_del(ui_Screen7);

// NULL screen variables
ui_Screen7= NULL;
ui_Panel11= NULL;
ui_Image6= NULL;
ui_Panel10= NULL;
ui_Label15= NULL;
ui_Label16= NULL;
ui_Panel15= NULL;
ui_Image7= NULL;
ui_Spinner2= NULL;

}
