// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#include "ui.h"

lv_obj_t *ui_Screen4 = NULL;lv_obj_t *ui_Button3 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Button4 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_Panel4 = NULL;lv_obj_t *ui_Image8 = NULL;
// event funtions

// build funtions

void ui_Screen4_screen_init(void)
{
ui_Screen4 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button3 = lv_btn_create(ui_Screen4);
lv_obj_set_width( ui_Button3, 183);
lv_obj_set_height( ui_Button3, 119);
lv_obj_set_x( ui_Button3, -123 );
lv_obj_set_y( ui_Button3, 57 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 2 );
lv_obj_set_y( ui_Label6, 2 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"English");
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button4 = lv_btn_create(ui_Screen4);
lv_obj_set_width( ui_Button4, 183);
lv_obj_set_height( ui_Button4, 119);
lv_obj_set_x( ui_Button4, 126 );
lv_obj_set_y( ui_Button4, 56 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xF54900), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Button4);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -1 );
lv_obj_set_y( ui_Label7, 2 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Hindi");
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_Screen4);
lv_obj_set_width( ui_Panel2, 450);
lv_obj_set_height( ui_Panel2, 86);
lv_obj_set_x( ui_Panel2, -3 );
lv_obj_set_y( ui_Panel2, -63 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, 0 );
lv_obj_set_y( ui_Label8, -16 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Choose Language");
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_Screen4);
lv_obj_set_width( ui_Panel4, 490);
lv_obj_set_height( ui_Panel4, 33);
lv_obj_set_x( ui_Panel4, 0 );
lv_obj_set_y( ui_Panel4, -144 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image8 = lv_img_create(ui_Panel4);
lv_img_set_src(ui_Image8, &ui_img_1046361127);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image8, -9 );
lv_obj_set_y( ui_Image8, -16 );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}

void ui_Screen4_screen_destroy(void)
{
   if (ui_Screen4) lv_obj_del(ui_Screen4);

// NULL screen variables
ui_Screen4= NULL;
ui_Button3= NULL;
ui_Label6= NULL;
ui_Button4= NULL;
ui_Label7= NULL;
ui_Panel2= NULL;
ui_Label8= NULL;
ui_Panel4= NULL;
ui_Image8= NULL;

}
