// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#include "ui.h"

lv_obj_t *ui_Screen11 = NULL;lv_obj_t *ui_Panel26 = NULL;lv_obj_t *ui_Image11 = NULL;lv_obj_t *ui_Panel25 = NULL;lv_obj_t *ui_Label35 = NULL;
// event funtions

// build funtions

void ui_Screen11_screen_init(void)
{
ui_Screen11 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen11, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel26 = lv_obj_create(ui_Screen11);
lv_obj_set_width( ui_Panel26, 45);
lv_obj_set_height( ui_Panel26, 33);
lv_obj_set_x( ui_Panel26, -214 );
lv_obj_set_y( ui_Panel26, -140 );
lv_obj_set_align( ui_Panel26, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel26, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel26, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel26, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel26, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel26, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image11 = lv_img_create(ui_Panel26);
lv_img_set_src(ui_Image11, &ui_img_1046361127);
lv_obj_set_width( ui_Image11, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image11, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image11, -9 );
lv_obj_set_y( ui_Image11, -16 );
lv_obj_add_flag( ui_Image11, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel25 = lv_obj_create(ui_Screen11);
lv_obj_set_width( ui_Panel25, 373);
lv_obj_set_height( ui_Panel25, 56);
lv_obj_set_x( ui_Panel25, 10 );
lv_obj_set_y( ui_Panel25, -113 );
lv_obj_set_align( ui_Panel25, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel25, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel25, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel25, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel25, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel25, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label35 = lv_label_create(ui_Panel25);
lv_obj_set_width( ui_Label35, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label35, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label35, -2 );
lv_obj_set_y( ui_Label35, -4 );
lv_obj_set_align( ui_Label35, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label35,"Scan and Pay");
lv_obj_set_style_text_font(ui_Label35, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen11_screen_destroy(void)
{
   if (ui_Screen11) lv_obj_del(ui_Screen11);

// NULL screen variables
ui_Screen11= NULL;
ui_Panel26= NULL;
ui_Image11= NULL;
ui_Panel25= NULL;
ui_Label35= NULL;

}
