// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#include "ui.h"

lv_obj_t *ui_Screen14 = NULL;

lv_obj_t *ui_Panel_scr14_back = NULL;
lv_obj_t *ui_Image_scr14_back = NULL;
lv_obj_t *ui_Label_scr14_title = NULL;
lv_obj_t *ui_Label_scr14_badge = NULL;

lv_obj_t *ui_Panel_sensor_bar = NULL;
lv_obj_t *ui_Label_sensor_ir = NULL;
lv_obj_t *ui_Label_sensor_temp = NULL;
lv_obj_t *ui_Label_sensor_hum = NULL;
lv_obj_t *ui_Btn_poll_ir = NULL;
lv_obj_t *ui_Label_poll_ir = NULL;

lv_obj_t *ui_Panel_actuators = NULL;
lv_obj_t *ui_Btn_test_m3 = NULL;
lv_obj_t *ui_Label_test_m3 = NULL;
lv_obj_t *ui_Btn_test_m4 = NULL;
lv_obj_t *ui_Label_test_m4 = NULL;
lv_obj_t *ui_Btn_test_r0 = NULL;
lv_obj_t *ui_Label_test_r0 = NULL;
lv_obj_t *ui_Btn_test_r1 = NULL;
lv_obj_t *ui_Label_test_r1 = NULL;

lv_obj_t *ui_Btn_test_step_fwd = NULL;
lv_obj_t *ui_Label_test_step_fwd = NULL;
lv_obj_t *ui_Btn_test_step_rev = NULL;
lv_obj_t *ui_Label_test_step_rev = NULL;
lv_obj_t *ui_Btn_test_gate = NULL;
lv_obj_t *ui_Label_test_gate = NULL;
lv_obj_t *ui_Btn_test_drop = NULL;
lv_obj_t *ui_Label_test_drop = NULL;

lv_obj_t *ui_Btn_test_auto_all = NULL;
lv_obj_t *ui_Label_test_auto_all = NULL;
lv_obj_t *ui_Btn_test_arm = NULL;
lv_obj_t *ui_Label_test_arm = NULL;
lv_obj_t *ui_Btn_test_estop = NULL;
lv_obj_t *ui_Label_test_estop = NULL;

static void ui_event_Panel_scr14_back_cb(lv_event_t * e) {
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen2_screen_init);
    }
}

void ui_Screen14_screen_init(void)
{
    ui_Screen14 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen14, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Screen14, lv_color_hex(0x0A1120), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ================= 1. HEADER BAR =================
    lv_obj_t *head_bar = lv_obj_create(ui_Screen14);
    lv_obj_set_width(head_bar, 472);
    lv_obj_set_height(head_bar, 34);
    lv_obj_set_x(head_bar, 0);
    lv_obj_set_y(head_bar, -139);
    lv_obj_set_align(head_bar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(head_bar, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(head_bar, lv_color_hex(0x131E30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(head_bar, lv_color_hex(0x22324A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(head_bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(head_bar, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(head_bar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Back Button
    ui_Panel_scr14_back = lv_obj_create(head_bar);
    lv_obj_set_width(ui_Panel_scr14_back, 42);
    lv_obj_set_height(ui_Panel_scr14_back, 28);
    lv_obj_set_align(ui_Panel_scr14_back, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Panel_scr14_back, 2);
    lv_obj_clear_flag(ui_Panel_scr14_back, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Panel_scr14_back, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_scr14_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Panel_scr14_back, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_scr14_back = lv_img_create(ui_Panel_scr14_back);
    lv_img_set_src(ui_Image_scr14_back, &ui_img_1046361127);
    lv_obj_set_align(ui_Image_scr14_back, LV_ALIGN_CENTER);

    ui_Label_scr14_title = lv_label_create(head_bar);
    lv_obj_set_align(ui_Label_scr14_title, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Label_scr14_title, 52);
    lv_label_set_text(ui_Label_scr14_title, "Hardware Motor & Sensor Test Console");
    lv_obj_set_style_text_color(ui_Label_scr14_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_scr14_title, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_scr14_badge = lv_label_create(head_bar);
    lv_obj_set_align(ui_Label_scr14_badge, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Label_scr14_badge, -8);
    lv_label_set_text(ui_Label_scr14_badge, "UNO: ARMED & READY");
    lv_obj_set_style_text_color(ui_Label_scr14_badge, lv_color_hex(0x05DF72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_scr14_badge, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ================= 2. LIVE SENSOR READOUT BAR =================
    ui_Panel_sensor_bar = lv_obj_create(ui_Screen14);
    lv_obj_set_width(ui_Panel_sensor_bar, 472);
    lv_obj_set_height(ui_Panel_sensor_bar, 44);
    lv_obj_set_x(ui_Panel_sensor_bar, 0);
    lv_obj_set_y(ui_Panel_sensor_bar, -95);
    lv_obj_set_align(ui_Panel_sensor_bar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_sensor_bar, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Panel_sensor_bar, lv_color_hex(0x131E30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_sensor_bar, lv_color_hex(0x22324A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_sensor_bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Panel_sensor_bar, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_Panel_sensor_bar, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_sensor_ir = lv_label_create(ui_Panel_sensor_bar);
    lv_obj_set_align(ui_Label_sensor_ir, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Label_sensor_ir, 8);
    lv_label_set_text(ui_Label_sensor_ir, "IR Beam (A3): CLEAR (1)");
    lv_obj_set_style_text_color(ui_Label_sensor_ir, lv_color_hex(0x05DF72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_sensor_ir, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_sensor_temp = lv_label_create(ui_Panel_sensor_bar);
    lv_obj_set_align(ui_Label_sensor_temp, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Label_sensor_temp, 175);
    lv_label_set_text(ui_Label_sensor_temp, "Temp: 3.8 C [DS18B20]");
    lv_obj_set_style_text_color(ui_Label_sensor_temp, lv_color_hex(0x00D2B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_sensor_temp, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_sensor_hum = lv_label_create(ui_Panel_sensor_bar);
    lv_obj_set_align(ui_Label_sensor_hum, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Label_sensor_hum, 318);
    lv_label_set_text(ui_Label_sensor_hum, "RH: 52% [DHT22]");
    lv_obj_set_style_text_color(ui_Label_sensor_hum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_sensor_hum, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn_poll_ir = lv_btn_create(ui_Panel_sensor_bar);
    lv_obj_set_width(ui_Btn_poll_ir, 38);
    lv_obj_set_height(ui_Btn_poll_ir, 32);
    lv_obj_set_align(ui_Btn_poll_ir, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Btn_poll_ir, -4);
    lv_obj_set_style_bg_color(ui_Btn_poll_ir, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Btn_poll_ir, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_poll_ir = lv_label_create(ui_Btn_poll_ir);
    lv_obj_set_align(ui_Label_poll_ir, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_poll_ir, "IR?");
    lv_obj_set_style_text_font(ui_Label_poll_ir, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ================= 3. ACTUATOR TESTING GRID =================
    ui_Panel_actuators = lv_obj_create(ui_Screen14);
    lv_obj_set_width(ui_Panel_actuators, 472);
    lv_obj_set_height(ui_Panel_actuators, 150);
    lv_obj_set_x(ui_Panel_actuators, 0);
    lv_obj_set_y(ui_Panel_actuators, 8);
    lv_obj_set_align(ui_Panel_actuators, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_actuators, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Panel_actuators, lv_color_hex(0x131E30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_actuators, lv_color_hex(0x22324A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_actuators, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Panel_actuators, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_Panel_actuators, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Row 1 (y = -35): BO Motors M3/M4 and Relays R0/R1
    ui_Btn_test_m3 = lv_btn_create(ui_Panel_actuators);
    lv_obj_set_width(ui_Btn_test_m3, 110);
    lv_obj_set_height(ui_Btn_test_m3, 62);
    lv_obj_set_x(ui_Btn_test_m3, -168);
    lv_obj_set_y(ui_Btn_test_m3, -35);
    lv_obj_set_align(ui_Btn_test_m3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Btn_test_m3, lv_color_hex(0x1A2840), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn_test_m3, lv_color_hex(0x2A3D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn_test_m3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Btn_test_m3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_test_m3 = lv_label_create(ui_Btn_test_m3);
    lv_obj_set_align(ui_Label_test_m3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_test_m3, "M3 Motor\n(Spring 1)");
    lv_obj_set_style_text_align(ui_Label_test_m3, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_font(ui_Label_test_m3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn_test_m4 = lv_btn_create(ui_Panel_actuators);
    lv_obj_set_width(ui_Btn_test_m4, 110);
    lv_obj_set_height(ui_Btn_test_m4, 62);
    lv_obj_set_x(ui_Btn_test_m4, -56);
    lv_obj_set_y(ui_Btn_test_m4, -35);
    lv_obj_set_align(ui_Btn_test_m4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Btn_test_m4, lv_color_hex(0x1A2840), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn_test_m4, lv_color_hex(0x2A3D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn_test_m4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Btn_test_m4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_test_m4 = lv_label_create(ui_Btn_test_m4);
    lv_obj_set_align(ui_Label_test_m4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_test_m4, "M4 Motor\n(Spring 2)");
    lv_obj_set_style_text_align(ui_Label_test_m4, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_font(ui_Label_test_m4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn_test_r0 = lv_btn_create(ui_Panel_actuators);
    lv_obj_set_width(ui_Btn_test_r0, 110);
    lv_obj_set_height(ui_Btn_test_r0, 62);
    lv_obj_set_x(ui_Btn_test_r0, 56);
    lv_obj_set_y(ui_Btn_test_r0, -35);
    lv_obj_set_align(ui_Btn_test_r0, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Btn_test_r0, lv_color_hex(0x1A2840), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn_test_r0, lv_color_hex(0x2A3D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn_test_r0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Btn_test_r0, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_test_r0 = lv_label_create(ui_Btn_test_r0);
    lv_obj_set_align(ui_Label_test_r0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_test_r0, "Relay R0\n(Slot 3)");
    lv_obj_set_style_text_align(ui_Label_test_r0, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_font(ui_Label_test_r0, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn_test_r1 = lv_btn_create(ui_Panel_actuators);
    lv_obj_set_width(ui_Btn_test_r1, 110);
    lv_obj_set_height(ui_Btn_test_r1, 62);
    lv_obj_set_x(ui_Btn_test_r1, 168);
    lv_obj_set_y(ui_Btn_test_r1, -35);
    lv_obj_set_align(ui_Btn_test_r1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Btn_test_r1, lv_color_hex(0x1A2840), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn_test_r1, lv_color_hex(0x2A3D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn_test_r1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Btn_test_r1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_test_r1 = lv_label_create(ui_Btn_test_r1);
    lv_obj_set_align(ui_Label_test_r1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_test_r1, "Relay R1\n(Slot 4)");
    lv_obj_set_style_text_align(ui_Label_test_r1, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_font(ui_Label_test_r1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Row 2 (y = 35): Stepper FWD/REV, Gate Servo, Drop Servo
    ui_Btn_test_step_fwd = lv_btn_create(ui_Panel_actuators);
    lv_obj_set_width(ui_Btn_test_step_fwd, 110);
    lv_obj_set_height(ui_Btn_test_step_fwd, 62);
    lv_obj_set_x(ui_Btn_test_step_fwd, -168);
    lv_obj_set_y(ui_Btn_test_step_fwd, 35);
    lv_obj_set_align(ui_Btn_test_step_fwd, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Btn_test_step_fwd, lv_color_hex(0x1A2840), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn_test_step_fwd, lv_color_hex(0x2A3D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn_test_step_fwd, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Btn_test_step_fwd, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_test_step_fwd = lv_label_create(ui_Btn_test_step_fwd);
    lv_obj_set_align(ui_Label_test_step_fwd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_test_step_fwd, "Rotor FWD\n(+512 Step)");
    lv_obj_set_style_text_align(ui_Label_test_step_fwd, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_font(ui_Label_test_step_fwd, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn_test_step_rev = lv_btn_create(ui_Panel_actuators);
    lv_obj_set_width(ui_Btn_test_step_rev, 110);
    lv_obj_set_height(ui_Btn_test_step_rev, 62);
    lv_obj_set_x(ui_Btn_test_step_rev, -56);
    lv_obj_set_y(ui_Btn_test_step_rev, 35);
    lv_obj_set_align(ui_Btn_test_step_rev, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Btn_test_step_rev, lv_color_hex(0x1A2840), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn_test_step_rev, lv_color_hex(0x2A3D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn_test_step_rev, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Btn_test_step_rev, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_test_step_rev = lv_label_create(ui_Btn_test_step_rev);
    lv_obj_set_align(ui_Label_test_step_rev, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_test_step_rev, "Rotor REV\n(-512 Step)");
    lv_obj_set_style_text_align(ui_Label_test_step_rev, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_font(ui_Label_test_step_rev, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn_test_gate = lv_btn_create(ui_Panel_actuators);
    lv_obj_set_width(ui_Btn_test_gate, 110);
    lv_obj_set_height(ui_Btn_test_gate, 62);
    lv_obj_set_x(ui_Btn_test_gate, 56);
    lv_obj_set_y(ui_Btn_test_gate, 35);
    lv_obj_set_align(ui_Btn_test_gate, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Btn_test_gate, lv_color_hex(0x1A2840), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn_test_gate, lv_color_hex(0x2A3D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn_test_gate, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Btn_test_gate, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_test_gate = lv_label_create(ui_Btn_test_gate);
    lv_obj_set_align(ui_Label_test_gate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_test_gate, "Gate Servo\n(Open/Close)");
    lv_obj_set_style_text_align(ui_Label_test_gate, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_font(ui_Label_test_gate, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn_test_drop = lv_btn_create(ui_Panel_actuators);
    lv_obj_set_width(ui_Btn_test_drop, 110);
    lv_obj_set_height(ui_Btn_test_drop, 62);
    lv_obj_set_x(ui_Btn_test_drop, 168);
    lv_obj_set_y(ui_Btn_test_drop, 35);
    lv_obj_set_align(ui_Btn_test_drop, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Btn_test_drop, lv_color_hex(0x1A2840), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn_test_drop, lv_color_hex(0x2A3D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn_test_drop, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Btn_test_drop, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_test_drop = lv_label_create(ui_Btn_test_drop);
    lv_obj_set_align(ui_Label_test_drop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_test_drop, "Drop Servo\n(Trigger)");
    lv_obj_set_style_text_align(ui_Label_test_drop, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_font(ui_Label_test_drop, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ================= 4. MASTER ACTION BUTTONS =================
    ui_Btn_test_auto_all = lv_btn_create(ui_Screen14);
    lv_obj_set_width(ui_Btn_test_auto_all, 200);
    lv_obj_set_height(ui_Btn_test_auto_all, 46);
    lv_obj_set_x(ui_Btn_test_auto_all, -135);
    lv_obj_set_y(ui_Btn_test_auto_all, 118);
    lv_obj_set_align(ui_Btn_test_auto_all, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Btn_test_auto_all, lv_color_hex(0x00A63E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn_test_auto_all, lv_color_hex(0x05DF72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn_test_auto_all, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Btn_test_auto_all, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_test_auto_all = lv_label_create(ui_Btn_test_auto_all);
    lv_obj_set_align(ui_Label_test_auto_all, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_test_auto_all, "AUTO-TEST ALL MOTORS");
    lv_obj_set_style_text_font(ui_Label_test_auto_all, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn_test_arm = lv_btn_create(ui_Screen14);
    lv_obj_set_width(ui_Btn_test_arm, 126);
    lv_obj_set_height(ui_Btn_test_arm, 46);
    lv_obj_set_x(ui_Btn_test_arm, 38);
    lv_obj_set_y(ui_Btn_test_arm, 118);
    lv_obj_set_align(ui_Btn_test_arm, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Btn_test_arm, lv_color_hex(0x1E293B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn_test_arm, lv_color_hex(0x334155), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn_test_arm, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Btn_test_arm, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_test_arm = lv_label_create(ui_Btn_test_arm);
    lv_obj_set_align(ui_Label_test_arm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_test_arm, "ARM / START");
    lv_obj_set_style_text_font(ui_Label_test_arm, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn_test_estop = lv_btn_create(ui_Screen14);
    lv_obj_set_width(ui_Btn_test_estop, 126);
    lv_obj_set_height(ui_Btn_test_estop, 46);
    lv_obj_set_x(ui_Btn_test_estop, 172);
    lv_obj_set_y(ui_Btn_test_estop, 118);
    lv_obj_set_align(ui_Btn_test_estop, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Btn_test_estop, lv_color_hex(0xDC2626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Btn_test_estop, lv_color_hex(0xEF4444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Btn_test_estop, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Btn_test_estop, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_test_estop = lv_label_create(ui_Btn_test_estop);
    lv_obj_set_align(ui_Label_test_estop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_test_estop, "STOP (E-STOP)");
    lv_obj_set_style_text_font(ui_Label_test_estop, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel_scr14_back, ui_event_Panel_scr14_back_cb, LV_EVENT_CLICKED, NULL);
}

void ui_Screen14_screen_destroy(void)
{
    if (ui_Screen14) lv_obj_del(ui_Screen14);
    ui_Screen14 = NULL;
    ui_Panel_scr14_back = NULL;
    ui_Image_scr14_back = NULL;
    ui_Label_scr14_title = NULL;
    ui_Label_scr14_badge = NULL;
    ui_Panel_sensor_bar = NULL;
    ui_Label_sensor_ir = NULL;
    ui_Label_sensor_temp = NULL;
    ui_Label_sensor_hum = NULL;
    ui_Btn_poll_ir = NULL;
    ui_Label_poll_ir = NULL;
    ui_Panel_actuators = NULL;
    ui_Btn_test_m3 = NULL;
    ui_Label_test_m3 = NULL;
    ui_Btn_test_m4 = NULL;
    ui_Label_test_m4 = NULL;
    ui_Btn_test_r0 = NULL;
    ui_Label_test_r0 = NULL;
    ui_Btn_test_r1 = NULL;
    ui_Label_test_r1 = NULL;
    ui_Btn_test_step_fwd = NULL;
    ui_Label_test_step_fwd = NULL;
    ui_Btn_test_step_rev = NULL;
    ui_Label_test_step_rev = NULL;
    ui_Btn_test_gate = NULL;
    ui_Label_test_gate = NULL;
    ui_Btn_test_drop = NULL;
    ui_Label_test_drop = NULL;
    ui_Btn_test_auto_all = NULL;
    ui_Label_test_auto_all = NULL;
    ui_Btn_test_arm = NULL;
    ui_Label_test_arm = NULL;
    ui_Btn_test_estop = NULL;
    ui_Label_test_estop = NULL;
}
