// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t *ui_Screen4;
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Image8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

