// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#include "ui.h"

lv_obj_t *ui_Screen12 = NULL;lv_obj_t *ui_Panel27 = NULL;lv_obj_t *ui_Image14 = NULL;lv_obj_t *ui_Panel28 = NULL;lv_obj_t *ui_Label39 = NULL;lv_obj_t *ui_Label41 = NULL;
// event funtions

// build funtions

void ui_Screen12_screen_init(void)
{
ui_Screen12 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen12, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel27 = lv_obj_create(ui_Screen12);
lv_obj_set_width( ui_Panel27, 45);
lv_obj_set_height( ui_Panel27, 33);
lv_obj_set_x( ui_Panel27, -214 );
lv_obj_set_y( ui_Panel27, -140 );
lv_obj_set_align( ui_Panel27, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel27, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel27, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel27, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel27, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel27, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image14 = lv_img_create(ui_Panel27);
lv_img_set_src(ui_Image14, &ui_img_1046361127);
lv_obj_set_width( ui_Image14, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image14, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image14, -9 );
lv_obj_set_y( ui_Image14, -16 );
lv_obj_add_flag( ui_Image14, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel28 = lv_obj_create(ui_Screen12);
lv_obj_set_width( ui_Panel28, 443);
lv_obj_set_height( ui_Panel28, 258);
lv_obj_set_x( ui_Panel28, 0 );
lv_obj_set_y( ui_Panel28, 11 );
lv_obj_set_align( ui_Panel28, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel28, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label39 = lv_label_create(ui_Panel28);
lv_obj_set_width( ui_Label39, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label39, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label39, -194 );
lv_obj_set_y( ui_Label39, -92 );
lv_obj_set_align( ui_Label39, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label39,"AI:- ");
lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0xF80019), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label39, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label41 = lv_label_create(ui_Panel28);
lv_obj_set_width( ui_Label41, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label41, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label41, 22 );
lv_obj_set_y( ui_Label41, -91 );
lv_obj_set_align( ui_Label41, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label41,"FEVER DETACHTED ,PLEASE TAKE YOUR MEDICIENE");

}

void ui_Screen12_screen_destroy(void)
{
   if (ui_Screen12) lv_obj_del(ui_Screen12);

// NULL screen variables
ui_Screen12= NULL;
ui_Panel27= NULL;
ui_Image14= NULL;
ui_Panel28= NULL;
ui_Label39= NULL;
ui_Label41= NULL;

}
