// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#ifndef UI_SCREEN14_H
#define UI_SCREEN14_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen14 - Hardware Diagnostics & Motor/Sensor Test Terminal
extern void ui_Screen14_screen_init(void);
extern void ui_Screen14_screen_destroy(void);
extern lv_obj_t *ui_Screen14;

// Header & Navigation
extern lv_obj_t *ui_Panel_scr14_back;
extern lv_obj_t *ui_Image_scr14_back;
extern lv_obj_t *ui_Label_scr14_title;
extern lv_obj_t *ui_Label_scr14_badge;

// Live Sensor Telemetry Panel
extern lv_obj_t *ui_Panel_sensor_bar;
extern lv_obj_t *ui_Label_sensor_ir;
extern lv_obj_t *ui_Label_sensor_temp;
extern lv_obj_t *ui_Label_sensor_hum;
extern lv_obj_t *ui_Btn_poll_ir;
extern lv_obj_t *ui_Label_poll_ir;

// Motor & Actuator Testing Grid
extern lv_obj_t *ui_Panel_actuators;
extern lv_obj_t *ui_Btn_test_m3;
extern lv_obj_t *ui_Label_test_m3;
extern lv_obj_t *ui_Btn_test_m4;
extern lv_obj_t *ui_Label_test_m4;
extern lv_obj_t *ui_Btn_test_r0;
extern lv_obj_t *ui_Label_test_r0;
extern lv_obj_t *ui_Btn_test_r1;
extern lv_obj_t *ui_Label_test_r1;

extern lv_obj_t *ui_Btn_test_step_fwd;
extern lv_obj_t *ui_Label_test_step_fwd;
extern lv_obj_t *ui_Btn_test_step_rev;
extern lv_obj_t *ui_Label_test_step_rev;
extern lv_obj_t *ui_Btn_test_gate;
extern lv_obj_t *ui_Label_test_gate;
extern lv_obj_t *ui_Btn_test_drop;
extern lv_obj_t *ui_Label_test_drop;

// Master Action Buttons (Auto-Test, E-Stop, Arm)
extern lv_obj_t *ui_Btn_test_auto_all;
extern lv_obj_t *ui_Label_test_auto_all;
extern lv_obj_t *ui_Btn_test_arm;
extern lv_obj_t *ui_Label_test_arm;
extern lv_obj_t *ui_Btn_test_estop;
extern lv_obj_t *ui_Label_test_estop;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
