// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#ifndef UI_SCREEN8_H
#define UI_SCREEN8_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen8
extern void ui_Screen8_screen_init(void);
extern void ui_Screen8_screen_destroy(void);
extern lv_obj_t *ui_Screen8;
extern lv_obj_t *ui_Panel16;
extern lv_obj_t *ui_Image9;
extern lv_obj_t *ui_Panel17;
extern lv_obj_t *ui_Label24;
extern lv_obj_t *ui_Label25;
extern lv_obj_t *ui_Panel18;
extern lv_obj_t *ui_Label26;
extern lv_obj_t *ui_Label27;
extern lv_obj_t *ui_Label28;
extern lv_obj_t *ui_Panel19;
extern lv_obj_t *ui_Label29;
extern lv_obj_t *ui_Label30;
extern lv_obj_t *ui_Label31;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

