// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#include "ui.h"

lv_obj_t *ui_Screen10 = NULL;lv_obj_t *ui_Panel14 = NULL;lv_obj_t *ui_Label37 = NULL;lv_obj_t *ui_Panel24 = NULL;lv_obj_t *ui_Image13 = NULL;lv_obj_t *ui_Panel23 = NULL;lv_obj_t *ui_Button2 = NULL;lv_obj_t *ui_Label23 = NULL;
// event funtions

// build funtions

void ui_Screen10_screen_init(void)
{
ui_Screen10 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen10, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel14 = lv_obj_create(ui_Screen10);
lv_obj_set_width( ui_Panel14, 450);
lv_obj_set_height( ui_Panel14, 86);
lv_obj_set_x( ui_Panel14, -3 );
lv_obj_set_y( ui_Panel14, -63 );
lv_obj_set_align( ui_Panel14, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label37 = lv_label_create(ui_Panel14);
lv_obj_set_width( ui_Label37, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label37, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label37, 0 );
lv_obj_set_y( ui_Label37, -24 );
lv_obj_set_align( ui_Label37, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label37,"VOICE");
lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel24 = lv_obj_create(ui_Screen10);
lv_obj_set_width( ui_Panel24, 45);
lv_obj_set_height( ui_Panel24, 33);
lv_obj_set_x( ui_Panel24, -214 );
lv_obj_set_y( ui_Panel24, -140 );
lv_obj_set_align( ui_Panel24, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel24, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel24, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel24, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel24, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel24, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image13 = lv_img_create(ui_Panel24);
lv_img_set_src(ui_Image13, &ui_img_1046361127);
lv_obj_set_width( ui_Image13, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image13, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image13, -9 );
lv_obj_set_y( ui_Image13, -16 );
lv_obj_add_flag( ui_Image13, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel23 = lv_obj_create(ui_Screen10);
lv_obj_set_width( ui_Panel23, 456);
lv_obj_set_height( ui_Panel23, 188);
lv_obj_set_x( ui_Panel23, 7 );
lv_obj_set_y( ui_Panel23, 42 );
lv_obj_set_align( ui_Panel23, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel23, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel23, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel23, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel23, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel23, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2 = lv_btn_create(ui_Panel23);
lv_obj_set_width( ui_Button2, 151);
lv_obj_set_height( ui_Button2, 148);
lv_obj_set_x( ui_Button2, 1 );
lv_obj_set_y( ui_Button2, 4 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button2, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x00F761), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label23 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label23, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label23,"START");
lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen10_screen_destroy(void)
{
   if (ui_Screen10) lv_obj_del(ui_Screen10);

// NULL screen variables
ui_Screen10= NULL;
ui_Panel14= NULL;
ui_Label37= NULL;
ui_Panel24= NULL;
ui_Image13= NULL;
ui_Panel23= NULL;
ui_Button2= NULL;
ui_Label23= NULL;

}
