// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#include "ui.h"

lv_obj_t *ui_Screen8 = NULL;lv_obj_t *ui_Panel16 = NULL;lv_obj_t *ui_Image9 = NULL;lv_obj_t *ui_Panel17 = NULL;lv_obj_t *ui_Label24 = NULL;lv_obj_t *ui_Label25 = NULL;lv_obj_t *ui_Panel18 = NULL;lv_obj_t *ui_Label26 = NULL;lv_obj_t *ui_Label27 = NULL;lv_obj_t *ui_Label28 = NULL;lv_obj_t *ui_Panel19 = NULL;lv_obj_t *ui_Label29 = NULL;lv_obj_t *ui_Label30 = NULL;lv_obj_t *ui_Label31 = NULL;
// event funtions

// build funtions

void ui_Screen8_screen_init(void)
{
ui_Screen8 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen8, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel16 = lv_obj_create(ui_Screen8);
lv_obj_set_width( ui_Panel16, 45);
lv_obj_set_height( ui_Panel16, 33);
lv_obj_set_x( ui_Panel16, -214 );
lv_obj_set_y( ui_Panel16, -140 );
lv_obj_set_align( ui_Panel16, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image9 = lv_img_create(ui_Panel16);
lv_img_set_src(ui_Image9, &ui_img_1046361127);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image9, -9 );
lv_obj_set_y( ui_Image9, -16 );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel17 = lv_obj_create(ui_Screen8);
lv_obj_set_width( ui_Panel17, 332);
lv_obj_set_height( ui_Panel17, 92);
lv_obj_set_x( ui_Panel17, 0 );
lv_obj_set_y( ui_Panel17, -67 );
lv_obj_set_align( ui_Panel17, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel17, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0x0F172B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label24 = lv_label_create(ui_Panel17);
lv_obj_set_width( ui_Label24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label24, -1 );
lv_obj_set_y( ui_Label24, -21 );
lv_obj_set_align( ui_Label24, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label24,"Measure SpO2  & Temp");
lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label25 = lv_label_create(ui_Panel17);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label25, 0 );
lv_obj_set_y( ui_Label25, 7 );
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"Place finger on sensor");
lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel18 = lv_obj_create(ui_Screen8);
lv_obj_set_width( ui_Panel18, 183);
lv_obj_set_height( ui_Panel18, 119);
lv_obj_set_x( ui_Panel18, -119 );
lv_obj_set_y( ui_Panel18, 63 );
lv_obj_set_align( ui_Panel18, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel18, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x00A63E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel18, lv_color_hex(0x00BC7D), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Label26 = lv_label_create(ui_Panel18);
lv_obj_set_width( ui_Label26, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label26, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label26, -1 );
lv_obj_set_y( ui_Label26, -36 );
lv_obj_set_align( ui_Label26, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label26,"SPo2");
lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label27 = lv_label_create(ui_Panel18);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label27, 1 );
lv_obj_set_y( ui_Label27, 5 );
lv_obj_set_align( ui_Label27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label27,"98%");
lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label28 = lv_label_create(ui_Panel18);
lv_obj_set_width( ui_Label28, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label28, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label28, -2 );
lv_obj_set_y( ui_Label28, 44 );
lv_obj_set_align( ui_Label28, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label28," Normal");

ui_Panel19 = lv_obj_create(ui_Screen8);
lv_obj_set_width( ui_Panel19, 183);
lv_obj_set_height( ui_Panel19, 119);
lv_obj_set_x( ui_Panel19, 113 );
lv_obj_set_y( ui_Panel19, 61 );
lv_obj_set_align( ui_Panel19, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel19, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0xF54900), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel19, lv_color_hex(0x00BC7D), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Label29 = lv_label_create(ui_Panel19);
lv_obj_set_width( ui_Label29, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label29, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label29, -1 );
lv_obj_set_y( ui_Label29, -36 );
lv_obj_set_align( ui_Label29, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label29,"Temp");
lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label30 = lv_label_create(ui_Panel19);
lv_obj_set_width( ui_Label30, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label30, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label30, 1 );
lv_obj_set_y( ui_Label30, 5 );
lv_obj_set_align( ui_Label30, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label30,"97.3°F");
lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label31 = lv_label_create(ui_Panel19);
lv_obj_set_width( ui_Label31, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label31, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label31, -2 );
lv_obj_set_y( ui_Label31, 44 );
lv_obj_set_align( ui_Label31, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label31," Normal");

}

void ui_Screen8_screen_destroy(void)
{
   if (ui_Screen8) lv_obj_del(ui_Screen8);

// NULL screen variables
ui_Screen8= NULL;
ui_Panel16= NULL;
ui_Image9= NULL;
ui_Panel17= NULL;
ui_Label24= NULL;
ui_Label25= NULL;
ui_Panel18= NULL;
ui_Label26= NULL;
ui_Label27= NULL;
ui_Label28= NULL;
ui_Panel19= NULL;
ui_Label29= NULL;
ui_Label30= NULL;
ui_Label31= NULL;

}
