// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: methxai

#ifndef UI_SCREEN10_H
#define UI_SCREEN10_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen10
extern void ui_Screen10_screen_init(void);
extern void ui_Screen10_screen_destroy(void);
extern lv_obj_t *ui_Screen10;
extern lv_obj_t *ui_Panel14;
extern lv_obj_t *ui_Label37;
extern lv_obj_t *ui_Panel24;
extern lv_obj_t *ui_Image13;
extern lv_obj_t *ui_Panel23;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label23;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

